# This rule is not used by the project labelator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the namespace.labelator.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: labelator
    app.kubernetes.io/managed-by: kustomize
  name: label-editor-role
rules:
- apiGroups:
  - namespace.labelator.io
  resources:
  - labels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - namespace.labelator.io
  resources:
  - labels/status
  verbs:
  - get
