apiVersion: namespace.labelator.io/v1alpha1
kind: Label
metadata:
  name: wildcard-label
spec:
  cleanupOnDelete: true
  namespaces:
    - '*'
  excludedNamespaces:
    - "kube-system"
  labels:
    test: "test"
